/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package internal;

import javax.swing.JFrame;
import javax.swing.WindowConstants;

/**
 *
 * @author Idrogios
 */
public class ChooseAnalysisPanel extends javax.swing.JPanel {

    /**
     * Creates new form ChooseAnalysisPanel
     */
    public ChooseAnalysisPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        monthlyAnalysisChoice = new javax.swing.JRadioButton();
        anualAnalysisChoice = new javax.swing.JRadioButton();
        chooseBtn = new javax.swing.JButton();

        btnGroup.add(monthlyAnalysisChoice);
        btnGroup.add(anualAnalysisChoice);

        monthlyAnalysisChoice.setText("??????? ???????");

        anualAnalysisChoice.setText("?????? ???????");

        chooseBtn.setText("???????");
        chooseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(monthlyAnalysisChoice)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(chooseBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(anualAnalysisChoice, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(monthlyAnalysisChoice)
                .addGap(18, 18, 18)
                .addComponent(anualAnalysisChoice)
                .addGap(57, 57, 57)
                .addComponent(chooseBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>                        

    private void chooseBtnActionPerformed(java.awt.event.ActionEvent evt) {                                          
       
        JFrame frame;
        
        if(anualAnalysisChoice.isSelected()) {
            frame = new AnnualAnalysis();
        } else {
            frame = new MonthlyAnalysis();
        }
        
        frame.setVisible(true);
        frame.pack();
    }                                         


    // Variables declaration - do not modify                     
    private javax.swing.JRadioButton anualAnalysisChoice;
    private javax.swing.ButtonGroup btnGroup;
    private javax.swing.JButton chooseBtn;
    private javax.swing.JRadioButton monthlyAnalysisChoice;
    // End of variables declaration                   

    public static void main(String[] args) {
        JFrame frame = new JFrame();
        frame.setContentPane(new ChooseAnalysisPanel());
        frame.setVisible(true);
        frame.pack();
        frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        
    }
}
